! FRR Configuration for Router R2
frr defaults traditional
hostname r2
log syslog
service integrated-vtysh-config
!
interface lo
 ip address 10.2.2.2/32
!
interface eth0
 ip address 10.100.2.1/24
!
line vty
!
