! FRR Configuration for Router R3
frr defaults traditional
hostname r3
log syslog
service integrated-vtysh-config
!
interface lo
 ip address 10.3.3.3/32
!
interface eth0
 ip address 10.100.3.1/24
!
line vty
!
